export enum EventNames {

    NODE_CREATED = "NODE_CREATED",
    
    STOCKS_CREATED = "STOCKS_CREATED",
    LOTS_CREATED = "LOTS_CREATED",
    LOT_UNIT_UPDATED = "LOT_UNIT_UPDATED",
    STOCK_ITEM_UNIT_UPDATED = "STOCK_ITEM_UNIT_UPDATED",

    PRODUCT_ITEMS_CREATED = "PRODUCT_ITEMS_CREATED"

}